Repository vultisig/vultisig-android, pull requests merged in 2024-06, with the labels that each got.

#286 Fix vault name screen
  app/src/main/java/com/vultisig/wallet/presenter/vault_setting/vault_edit/VaultRenameScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/components/NamingComponent.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/NamingVaultScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#290 Add debounce functionality to handle rapid clicks
  app/src/main/java/com/vultisig/wallet/presenter/common/Onclick.kt
  app/src/main/java/com/vultisig/wallet/presenter/settings/currency_unit_setting/CurrencyUnitSettingScreen.kt
  app/src/main/java/com/vultisig/wallet/presenter/settings/language_setting/LanguageSettingScreen.kt
  app/src/main/java/com/vultisig/wallet/presenter/settings/settings_main/SettingsScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/components/ChainAccountItem.kt
  app/src/main/java/com/vultisig/wallet/ui/components/NetworkPrompts.kt
  app/src/main/java/com/vultisig/wallet/ui/components/SettingsItem.kt
  app/src/main/java/com/vultisig/wallet/ui/components/UiIcon.kt
  app/src/main/java/com/vultisig/wallet/ui/components/UiPlusButton.kt
  app/src/main/java/com/vultisig/wallet/ui/components/VaultActionButton.kt
  app/src/main/java/com/vultisig/wallet/ui/components/VaultCeil.kt
  app/src/main/java/com/vultisig/wallet/ui/components/multi_color_button.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/ScanQrScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/home/HomeScreen.kt
Labels: bug

#292 Add biometric auth
  app/build.gradle.kts
  app/src/main/java/com/vultisig/wallet/app/activity/MainActivity.kt
  app/src/main/java/com/vultisig/wallet/ui/components/BiometryAuthPrompt.kt
  app/src/main/java/com/vultisig/wallet/ui/utils/Context.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: Feature

#300 Cache token balance and prices in Room
  app/src/main/java/com/vultisig/wallet/data/db/AppDatabase.kt
  app/src/main/java/com/vultisig/wallet/data/db/DatabaseModule.kt
  app/src/main/java/com/vultisig/wallet/data/db/dao/TokenPriceDao.kt
  app/src/main/java/com/vultisig/wallet/data/db/dao/TokenValueDao.kt
  app/src/main/java/com/vultisig/wallet/data/db/migrations/MIGRATIONS.kt
  app/src/main/java/com/vultisig/wallet/data/db/models/TokenPriceEntity.kt
  app/src/main/java/com/vultisig/wallet/data/db/models/TokenValueEntity.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/AccountsRepository.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/BalanceRepository.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/TokenPriceRepository.kt
Labels: enhancement

#302 Add swap screen UI
  app/src/main/java/com/vultisig/wallet/app/activity/MainActivity.kt
  app/src/main/java/com/vultisig/wallet/presenter/settings/faq_setting/FAQSettingScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/components/VaultCeil.kt
  app/src/main/java/com/vultisig/wallet/ui/components/library/form/Form.kt
  app/src/main/java/com/vultisig/wallet/ui/components/library/form/FormTokenSelection.kt
  app/src/main/java/com/vultisig/wallet/ui/components/multi_color_button.kt
  app/src/main/java/com/vultisig/wallet/ui/models/ChainTokensViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/VaultAccountsViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/send/SendFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/navigation/NavGraph.kt
  app/src/main/java/com/vultisig/wallet/ui/navigation/Navigation.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/ChainTokensScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/TransactionDoneScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/send/SendFormScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/send/VerifyTransactionScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapFormScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/utils/PreviewMocks.kt
  app/src/main/res/drawable/ic_swap_arrows.xml
  app/src/main/res/values/strings.xml
Labels: Feature

#320 Add verify swap UI
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/VerifySwapViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/send/VerifyTransactionScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/VerifySwapScreen.kt
  app/src/main/res/values/strings.xml
Labels: Feature

#328 Add swap keysign
  app/src/main/java/com/vultisig/wallet/chains/EvmHelper.kt
  app/src/main/java/com/vultisig/wallet/chains/THORCHainHelper.kt
  app/src/main/java/com/vultisig/wallet/chains/THORChainSwaps.kt
  app/src/main/java/com/vultisig/wallet/data/DataModule.kt
  app/src/main/java/com/vultisig/wallet/data/models/SwapQuote.kt
  app/src/main/java/com/vultisig/wallet/data/models/SwapTransaction.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/BlockChainSpecificRepository.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/RepositoriesModule.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/SwapQuoteRepository.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/SwapTransactionRepository.kt
  app/src/main/java/com/vultisig/wallet/data/usecases/ConvertTokenAndValueToTokenValueUseCase.kt
  app/src/main/java/com/vultisig/wallet/data/usecases/UseCasesModule.kt
  app/src/main/java/com/vultisig/wallet/models/THORChainSwapPayload.kt
  app/src/main/java/com/vultisig/wallet/models/swap/THORChainSwapQuote.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignFlowViewModel.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignPayload.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignShareViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/components/NetworkPrompts.kt
  app/src/main/java/com/vultisig/wallet/ui/models/send/SendFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
Labels: Feature

#336 Fix load balance timeout
  app/src/main/java/com/vultisig/wallet/data/api/EvmApi.kt
Labels: bug

#334 Implement digit string to words conversion for dynamic string resources
  app/src/main/java/com/vultisig/wallet/presenter/keygen/DeviceList.kt
  app/src/main/java/com/vultisig/wallet/ui/components/DigitString.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#343 Add transaction data to verify swap screen
  app/src/main/java/com/vultisig/wallet/common/UiText.kt
  app/src/main/java/com/vultisig/wallet/data/models/SwapTransaction.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/VerifySwapViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/VerifySwapScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#347 Query quote with empty amount
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
Labels: enhancement

#349 Fix transaction done navigation crash
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
Labels: crash

#360 Show KeysignPayload data in VerifySwapScreen when joining keysign
  app/src/main/java/com/vultisig/wallet/models/THORChainSwapPayload.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/JoinKeysignViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/keysign/JoinKeysignView.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/VerifySwapScreen.kt
Labels: enhancement

#348 Feature: Implement QR Code Sharing Functionality In Swap Screen
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
Labels: Feature

#376 Clear focus on FormTextField ImeAction
  app/src/main/java/com/vultisig/wallet/ui/components/library/form/Form.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapFormScreen.kt
Labels: enhancement

#385 Co-sign 1inch swap
  app/src/main/java/com/vultisig/wallet/chains/EvmHelper.kt
  app/src/main/java/com/vultisig/wallet/data/wallet/OneInchSwap.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignPayload.kt
Labels: Feature

#413 Add initiating approval keysign
  app/src/main/java/com/vultisig/wallet/common/KeyOrderLocation.kt
  app/src/main/java/com/vultisig/wallet/data/api/EvmApi.kt
  app/src/main/java/com/vultisig/wallet/data/models/SwapTransaction.kt
  app/src/main/java/com/vultisig/wallet/data/models/TokenStandard.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/AllowanceRepository.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/RepositoriesModule.kt
  app/src/main/java/com/vultisig/wallet/models/Chain.kt
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignShareViewModel.kt
  app/src/main/java/com/vultisig/wallet/presenter/settings/default_chains_setting/DefaultChainsUiModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/navigation/SendDst.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
Labels: enhancement

#418 Add verify approve screen
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/VerifyApproveViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/navigation/SendDst.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/SwapScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/swap/VerifyApproveScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#407 Feature: Calculate Percent Amount in Send Screen
  app/src/main/java/com/vultisig/wallet/ui/components/PercentText.kt
  app/src/main/java/com/vultisig/wallet/ui/components/library/form/Form.kt
  app/src/main/java/com/vultisig/wallet/ui/models/send/SendFormViewModel.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/send/SendFormScreen.kt
  app/src/main/res/values/strings.xml
Labels: enhancement, Feature

#443 Implemented Localization for 'This Device' Identifier in Vault Details
  app/src/main/java/com/vultisig/wallet/presenter/vault_setting/vault_detail/VaultDetailViewmodel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, Feature

#437 Improve Debounce Click Handling
  app/src/main/java/com/vultisig/wallet/presenter/common/Onclick.kt
  app/src/main/java/com/vultisig/wallet/presenter/import_file/ImportFileScreen.kt
  app/src/main/java/com/vultisig/wallet/ui/components/VaultCeil.kt
  app/src/main/java/com/vultisig/wallet/ui/screens/vault_settings/components/ConfirmDeleteScreen.kt
Labels: bug

#459 Implement language change without app restart
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/vultisig/wallet/presenter/settings/language_setting/LanguageSettingScreen.kt
Labels: bug

#467 Fix Vault Click Bug
  app/src/main/java/com/vultisig/wallet/ui/components/VaultCeil.kt
Labels: bug, High Priority

#482 Remove Share Icon from keysign state in send screen
  app/src/main/java/com/vultisig/wallet/presenter/keysign/KeysignFlow.kt
Labels: invalid, High Priority
