Repository vultisig/vultisig-android, pull requests merged in 2024-08, with the labels that each got.

#674 Remove BCH prefix
  app/src/main/java/com/vultisig/wallet/data/db/AppDatabase.kt
  app/src/main/java/com/vultisig/wallet/data/db/DatabaseModule.kt
  app/src/main/java/com/vultisig/wallet/data/db/migrations/MIGRATIONS.kt
  app/src/main/java/com/vultisig/wallet/data/mappers/VaultIOSToAndroidMapper.kt
  app/src/main/java/com/vultisig/wallet/data/repositories/ChainAccountAddressRepository.kt
Labels: enhancement

#710 Update maya stream swap interval
  app/src/main/java/com/vultisig/wallet/data/repositories/SwapQuoteRepository.kt
  app/src/main/java/com/vultisig/wallet/ui/models/swap/SwapFormViewModel.kt
Labels: enhancement, feature

#711 Fix onboarding not showing 4th page
  app/src/main/java/com/vultisig/wallet/presenter/welcome/WelcomeScreen.kt
Labels: bug
